{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.existingClaim -}}
{{- $fullName := include "common-chart.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.name | default (printf "%s-pvc" $fullName) }}
  namespace: {{ template "common-chart.namespace" . }}
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
{{- if .Values.persistence.additionalLabels }}
{{ toYaml .Values.persistence.additionalLabels | indent 4 }}
{{- end }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  {{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
  {{- end }}
{{- end }}
{{- end }}
