{{- if .Values.serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "common-chart.name" .) .Values.serviceAccount.name }}
  namespace: {{ template "common-chart.namespace" . }}
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
